### ISSUE TITLE
error: no member named 'to_string' in namespace 'std'

### ISSUE THREAD

**Issue by sonukapoor** [s-a/iso-8583#7]
Hi, 

I am trying to install this package on macos, but receiving the above error. Please see below details. 

MacBook-Pro:code skapoor$ npm i iso-8583

> iso-8583@1.0.4 install /Users/skapoor/development/sandbox/XXXXXXcode/node_modules/iso-8583
> node-gyp rebuild

  CXX(target) Release/obj.target/ISO8583/NativeExtension.o
  CXX(target) Release/obj.target/ISO8583/functions.o
../functions.cc:109:26: error: no member named 'to_string' in namespace 'std'
                                std::string k = std::to_string(i);
                                                ~~~~~^
In file included from ../functions.cc:1:
../functions.h:34:12: warning: private field 'value_' is not used [-Wunused-private-field]
    double value_;
           ^
1 warning and 1 error generated.
make: *** [Release/obj.target/ISO8583/functions.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/skapoor/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/skapoor/.nvm/versions/node/v6.11.1/bin/node" "/Users/skapoor/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/skapoor/development/sandbox/XXXXXXX/code/node_modules/iso-8583
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN code@1.0.0 No description
npm WARN code@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iso-8583@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iso-8583@1.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely

Here is some more information about my system:

node -v: v6.11.1
uname -a: Darwin MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
cc -v: Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Any idea what I am missing? I have the latest xcode version installed.

**Comment by s-a** [comment]
Thanks to timgabets this should be fixed since v1.0.7. @timgabets  @sonukapoor can some one confirm this on OS X so that we can close this issue?
